# Create this environment with:
#   conda env create -y -f conda.yaml
# To activate this environment, use:
#   conda activate pals
name: pals

channels:
  - conda-forge
  - nodefaults

dependencies:
  - docutils
  - python
  - myst-parser
  - pip
  - pybtex
  - pygments
  - recommonmark
  - sphinx
  - sphinx-autobuild
  - sphinx-book-theme
  - sphinx-copybutton
  - sphinx-design
  - sphinxcontrib-bibtex
  - sphinxcontrib-svg2pdfconverter-with-all
  - sphinxcontrib-napoleon
# - sphinx_rtd_theme
